return {
  { import = "plugins.colorscheme" },
  { import = "plugins.treesitter" },
  { import = "plugins.treesitter-context" },
  { import = "plugins.bufferline" },
  { import = "plugins.cmp" },
  { import = "plugins.lspconfig" },
  { import = "plugins.lazydev" },
  { import = "plugins.telescope" },
  { import = "plugins.which-key" },
  { import = "plugins.diffview" },
  { import = "plugins.gitsigns" },
  { import = "plugins.trouble" },
  { import = "plugins.lualine" },
  { import = "plugins.noice" },
  { import = "plugins.todo-comments" },
  { import = "plugins.oil" },
  { import = "plugins.harpoon" },
  { import = "plugins.devicons" },
  { import = "plugins.nvim-tree" },
  { import = "plugins.copilot" },
  { import = "plugins.fugitive" },
  { import = "plugins.sleuth" },
  { import = "plugins.undotree" },
  { import = "plugins.fidget" },
  { import = "plugins.claude-code" },
}
